include $(PWD)/rules_gp32

DEFINES := \
	-DPLATFORM_$(PLATFORM) \

DEVKITARM=/c/devkitGP32/devkitarm

DEVKITPRO=$(DEVKITARM)/..

TOOLPATH=$(DEVKITARM)/bin
PREFIX		:=	arm-linux-


CFLAGS	:=	-Wall -O2 -mtune=arm9tdmi\
 			-fomit-frame-pointer\
			-ffast-math $(INCLUDE)\
			$(DEFINES) -I$(PWD)/../sources

CXXFLAGS:=	-fexceptions $(CFLAGS)
LIBS	:=	-lmirkoSDK -laddon -lm
LIBDIRS	:=	$(LIBMIRKO)
EXTENSION:= fxe
