-include $(PWD)/rules_base

DEFINES := \
	-DPLATFORM_$(PLATFORM) \
	-DCPP_MEMORY \
	-D_NDEBUG \
	-D_NO_JACK_ \
	-D__LINUX_ALSA__ \
	-D__LINUX_ALSASEQ__

CFLAGS := -O3  -Wall $(DEFINES) -I/usr/local/include -I$(PWD)/../sources
CXXFLAGS:= $(CFLAGS)
LIBS	:= -lasound -lSDL -lpthread
EXTENSION:= rpi-exe

%.rpi-exe: $(OFILES)
	$(CXX) -o $(LDFLAGS) $@ $(OFILES) $(LIBS)
