-include $(PWD)/rules_base

# config
DEFINES := \
	-DCPP_MEMORY \
	-D__LINUX_ALSA__ \
	-D__LINUX_ALSASEQ__ \
	-DJACKAUDIO \
	-DRTAUDIO \
	-DRTMIDI

# optimization
CFLAGS := -m32 -O3 -Wall -I/usr/local/include -I$(PWD)/../sources
CXXFLAGS := $(CFLAGS)
LIBS := -L/local/lib -Wl,-rpath,/usr/local/lib -lasound -lSDL -ljack -lpthread
LDFLAGS := -m32
OUTPUT = ../lgpt
EXTENSION := x86

# build rule
%.x86: $(OFILES)
	$(CXX) $(LDFLAGS) -o $@ $(OFILES) $(LIBS)
