-include $(PWD)/rules_base

DEFINES := \
	-DPLATFORM_DINGOO \
	-DCPP_MEMORY \
	-D_NDEBUG \
	-D_NO_JACK_ \
	-D__LINUX_OSS__ \
	-DRS97 \
	-DUSB_TTY

DEVKIT=/opt/mipsel-rg350-linux-uclibc_sdk-buildroot

STRIP = ls
TOOLPATH=$(DEVKIT)/usr/bin
PREFIX		:=	mipsel-linux-
SDL_BASE = /opt/mipsel-rg350-linux-uclibc_sdk-buildroot/usr/mipsel-rg350-linux-uclibc/sysroot/usr/bin/

CFLAGS	:=	`$(SDL_BASE)sdl-config --cflags` -O3 $(DEFINES) -Wall -I$(PWD)/../sources
CXXFLAGS:=	$(CFLAGS) -std=gnu++03
LIBS	:=  -lSDL -lpthread 
LIBDIRS	:=	$(DEKVIT)/usr/lib
TARGET = lgpt.dge
EXTENSION:= dge

%.dge: $(OFILES)
	$(CXX) $(LDFLAGS) -o $@ $(OFILES) $(LIBS)
	@$(STRIP) $@
