-include $(PWD)/rules_base

DEFINES := \
	-DPLATFORM_$(PLATFORM) \
	-DCPP_MEMORY \
	-D_DEBUG \
	-D__LINUX_ALSA__  

DEVKIT=/opt/mipsel-linux-uclibc

TOOLPATH=$(DEVKIT)/usr/bin
PREFIX		:=	mipsel-linux-
STRIP = ls
SDL_BASE = /opt/mipsel-linux-uclibc/usr/bin/

CFLAGS	:=	`$(SDL_BASE)sdl-config --cflags` -O3 -Wall $(DEFINES) -I$(PWD)/../sources 
CXXFLAGS:=	$(CFLAGS)
LIBS	:=  -L/opt/mipsel-linux-uclibc/usr/lib -lSDL -lpthread 
LIBDIRS	:=	$(DEKVIT)/usr/lib
EXTENSION:= dge

%.dge: $(OFILES)
	$(CXX) $(LDFLAGS) -o $@ $(OFILES) $(LIBS)
	@$(STRIP) $@
