-include $(PWD)/rules_base

DEFINES := \
	-DPLATFORM_$(PLATFORM) \
	-DCPP_MEMORY \
	-DNDEBUG \
	-D__LINUX_OSS__

DEVKITARM=/c/devkitGP2X
DEVKITPRO=$(DEVKITARM)/..
STRIP = arm-linux-strip
TOOLPATH=$(DEVKITARM)/bin
PREFIX		:=	arm-linux-
SDL_BASE = C:/devkitGP2X/bin/arm-linux-

CFLAGS	:=	$(DEFINES) `$(SDL_BASE)sdl-config --cflags` -O2 -Wall -I$(PWD)/../sources 
CXXFLAGS:=	$(CFLAGS)
LIBS	:=  -L$(PWD)/../libs/GP2XSDL/ -lSDL -lpthread 
LIBDIRS	:=	$(DEKVITPRO)/lib
EXTENSION:= gpe

%.gpe: $(OFILES)
	$(CXX) -static $(LDFLAGS) -o $@ $(OFILES) $(LIBS)
	@$(STRIP) $@
