-include $(PWD)/rules_base

DEFINES := \
	-DPLATFORM_$(PLATFORM) \
	-DCPP_MEMORY \
	-DDEBUG \
	-D__LINUX_ALSA__ \
	-D_NO_JACK_  

DEVKIT=/usr/local/angstrom/arm

TOOLPATH=$(DEVKIT)/bin
PREFIX		:=	arm-angstrom-linux-gnueabi-

SDLBASE:= /home/nostromo/devtree/syntharchitecture/Libs/Beagleboard/SDL/
CFLAGS	:= -I$(SDLBASE)/include	$(DEFINES) -O3 -Wall -I$(PWD)/../sources
CXXFLAGS:=	$(CFLAGS)
LIBS	:=  -L$(SDLBASE)/lib -L/opt/mipsel-linux-uclibc/usr/lib -lSDL -ldirectfb -lasound -lpthread -ldl -lts
LIBDIRS	:=	$(DEKVIT)/usr/lib
EXTENSION:= beagle-exe

%.beagle-exe: $(OFILES)
	$(CXX) $(LDFLAGS) $@ $(OFILES) $(LIBS)
