include $(PWD)/rules_base

DEFINES := \
	-DPLATFORM_$(PLATFORM) \
	-D_DEBUG \
	-DDEBUG \
	-DFFMPEG_ENABLED

WTOOLPATH=C:\MinGW\bin
PREFIX := 

CFLAGS	:= -mthreads -g -Wall $(INCLUDES) $(DEFINES) -I$(PWD)/../sources
CXXFLAGS:= $(CFLAGS)
LDFLAGS := -L../libs/Wsdl-mingw
LIBS     :=  -lmingw32 -lSDL -lSDLmain -mwindows -luser32 -lgdi32 -lwinmm -ldxguid
EXTENSION:= exe
